version: '2.4'

services:
  server:
    build: .
    restart: unless-stopped
    cpus: 2
    mem_limit: 4G
    pids_limit: 512
    ports:
      - "50051:50051"
    environment:
      PG_DSN: 'host=db user=flexinpoint password=flexinpoint dbname=flexinpoint port=5432 sslmode=disable'
    depends_on:
      - db

  db:
    image: postgres:15-alpine3.16
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'flexinpoint'
      POSTGRES_PASSWORD: 'flexinpoint'
      POSTGRES_DB: 'flexinpoint'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./vol/db:/var/lib/postgresql/data
