// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: tenders/tenders.proto

package tenders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RequiredReputation float32                `protobuf:"fixed32,4,opt,name=required_reputation,json=requiredReputation,proto3" json:"required_reputation,omitempty"`
	Winner             string                 `protobuf:"bytes,5,opt,name=winner,proto3" json:"winner,omitempty"`
	Author             string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	Private            bool                   `protobuf:"varint,7,opt,name=private,proto3" json:"private,omitempty"`
	Finished           bool                   `protobuf:"varint,8,opt,name=finished,proto3" json:"finished,omitempty"`
	ProgramInput       string                 `protobuf:"bytes,9,opt,name=program_input,json=programInput,proto3" json:"program_input,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Tender) Reset() {
	*x = Tender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tender) ProtoMessage() {}

func (x *Tender) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tender.ProtoReflect.Descriptor instead.
func (*Tender) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{0}
}

func (x *Tender) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tender) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tender) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tender) GetRequiredReputation() float32 {
	if x != nil {
		return x.RequiredReputation
	}
	return 0
}

func (x *Tender) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *Tender) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Tender) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *Tender) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *Tender) GetProgramInput() string {
	if x != nil {
		return x.ProgramInput
	}
	return ""
}

func (x *Tender) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Bid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenderId    string  `protobuf:"bytes,2,opt,name=tender_id,json=tenderId,proto3" json:"tender_id,omitempty"`
	Price       float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Description string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Program     string  `protobuf:"bytes,5,opt,name=program,proto3" json:"program,omitempty"`
}

func (x *Bid) Reset() {
	*x = Bid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{1}
}

func (x *Bid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bid) GetTenderId() string {
	if x != nil {
		return x.TenderId
	}
	return ""
}

func (x *Bid) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Bid) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bid) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

type Tender_CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tender *Tender `protobuf:"bytes,1,opt,name=tender,proto3" json:"tender,omitempty"`
}

func (x *Tender_CreateRequest) Reset() {
	*x = Tender_CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tender_CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tender_CreateRequest) ProtoMessage() {}

func (x *Tender_CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tender_CreateRequest.ProtoReflect.Descriptor instead.
func (*Tender_CreateRequest) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Tender_CreateRequest) GetTender() *Tender {
	if x != nil {
		return x.Tender
	}
	return nil
}

type Tender_CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tender *Tender `protobuf:"bytes,1,opt,name=tender,proto3" json:"tender,omitempty"`
}

func (x *Tender_CreateResponse) Reset() {
	*x = Tender_CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tender_CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tender_CreateResponse) ProtoMessage() {}

func (x *Tender_CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tender_CreateResponse.ProtoReflect.Descriptor instead.
func (*Tender_CreateResponse) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Tender_CreateResponse) GetTender() *Tender {
	if x != nil {
		return x.Tender
	}
	return nil
}

type Tender_GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Tender_GetRequest) Reset() {
	*x = Tender_GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tender_GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tender_GetRequest) ProtoMessage() {}

func (x *Tender_GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tender_GetRequest.ProtoReflect.Descriptor instead.
func (*Tender_GetRequest) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Tender_GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Tender_GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tender *Tender `protobuf:"bytes,1,opt,name=tender,proto3" json:"tender,omitempty"`
}

func (x *Tender_GetResponse) Reset() {
	*x = Tender_GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tender_GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tender_GetResponse) ProtoMessage() {}

func (x *Tender_GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tender_GetResponse.ProtoReflect.Descriptor instead.
func (*Tender_GetResponse) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Tender_GetResponse) GetTender() *Tender {
	if x != nil {
		return x.Tender
	}
	return nil
}

type Tender_CloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Tender_CloseRequest) Reset() {
	*x = Tender_CloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tender_CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tender_CloseRequest) ProtoMessage() {}

func (x *Tender_CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tender_CloseRequest.ProtoReflect.Descriptor instead.
func (*Tender_CloseRequest) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Tender_CloseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Tender_CloseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinningBid *Bid `protobuf:"bytes,1,opt,name=winning_bid,json=winningBid,proto3" json:"winning_bid,omitempty"`
}

func (x *Tender_CloseResponse) Reset() {
	*x = Tender_CloseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tender_CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tender_CloseResponse) ProtoMessage() {}

func (x *Tender_CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tender_CloseResponse.ProtoReflect.Descriptor instead.
func (*Tender_CloseResponse) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Tender_CloseResponse) GetWinningBid() *Bid {
	if x != nil {
		return x.WinningBid
	}
	return nil
}

type Bid_CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid *Bid `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *Bid_CreateRequest) Reset() {
	*x = Bid_CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid_CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid_CreateRequest) ProtoMessage() {}

func (x *Bid_CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid_CreateRequest.ProtoReflect.Descriptor instead.
func (*Bid_CreateRequest) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Bid_CreateRequest) GetBid() *Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type Bid_CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid *Bid `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *Bid_CreateResponse) Reset() {
	*x = Bid_CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid_CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid_CreateResponse) ProtoMessage() {}

func (x *Bid_CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid_CreateResponse.ProtoReflect.Descriptor instead.
func (*Bid_CreateResponse) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Bid_CreateResponse) GetBid() *Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type Bid_ExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Bid_ExecuteRequest) Reset() {
	*x = Bid_ExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid_ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid_ExecuteRequest) ProtoMessage() {}

func (x *Bid_ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid_ExecuteRequest.ProtoReflect.Descriptor instead.
func (*Bid_ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Bid_ExecuteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Bid_ExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output  string               `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Ops     uint32               `protobuf:"varint,2,opt,name=ops,proto3" json:"ops,omitempty"`
	Elapsed *durationpb.Duration `protobuf:"bytes,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Error   string               `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Bid_ExecuteResponse) Reset() {
	*x = Bid_ExecuteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tenders_tenders_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid_ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid_ExecuteResponse) ProtoMessage() {}

func (x *Bid_ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenders_tenders_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid_ExecuteResponse.ProtoReflect.Descriptor instead.
func (*Bid_ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_tenders_tenders_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Bid_ExecuteResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Bid_ExecuteResponse) GetOps() uint32 {
	if x != nil {
		return x.Ops
	}
	return 0
}

func (x *Bid_ExecuteResponse) GetElapsed() *durationpb.Duration {
	if x != nil {
		return x.Elapsed
	}
	return nil
}

func (x *Bid_ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_tenders_tenders_proto protoreflect.FileDescriptor

var file_tenders_tenders_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf6, 0x04, 0x0a, 0x06, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x72,
	0x65, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x12, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x70, 0x75, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x1a, 0x38, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x74, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x1a, 0x39, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2e,
	0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x1a, 0x1c,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x36, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x74,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x74, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x1a, 0x1e, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x1a, 0x3e, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0b, 0x77, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x5f, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x0a, 0x77, 0x69, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x42, 0x69, 0x64, 0x4a, 0x04, 0x08, 0x0b, 0x10, 0x65, 0x22, 0x92, 0x03, 0x0a, 0x03, 0x42,
	0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x1a, 0x2f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x03, 0x62,
	0x69, 0x64, 0x1a, 0x30, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x69, 0x64, 0x52,
	0x03, 0x62, 0x69, 0x64, 0x1a, 0x20, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x86, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6f, 0x70, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x66, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x42, 0x0c,
	0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0xa2, 0x02, 0x03,
	0x54, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0xca, 0x02, 0x07,
	0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0xe2, 0x02, 0x13, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07,
	0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tenders_tenders_proto_rawDescOnce sync.Once
	file_tenders_tenders_proto_rawDescData = file_tenders_tenders_proto_rawDesc
)

func file_tenders_tenders_proto_rawDescGZIP() []byte {
	file_tenders_tenders_proto_rawDescOnce.Do(func() {
		file_tenders_tenders_proto_rawDescData = protoimpl.X.CompressGZIP(file_tenders_tenders_proto_rawDescData)
	})
	return file_tenders_tenders_proto_rawDescData
}

var file_tenders_tenders_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tenders_tenders_proto_goTypes = []interface{}{
	(*Tender)(nil),                // 0: tenders.Tender
	(*Bid)(nil),                   // 1: tenders.Bid
	(*Tender_CreateRequest)(nil),  // 2: tenders.Tender.CreateRequest
	(*Tender_CreateResponse)(nil), // 3: tenders.Tender.CreateResponse
	(*Tender_GetRequest)(nil),     // 4: tenders.Tender.GetRequest
	(*Tender_GetResponse)(nil),    // 5: tenders.Tender.GetResponse
	(*Tender_CloseRequest)(nil),   // 6: tenders.Tender.CloseRequest
	(*Tender_CloseResponse)(nil),  // 7: tenders.Tender.CloseResponse
	(*Bid_CreateRequest)(nil),     // 8: tenders.Bid.CreateRequest
	(*Bid_CreateResponse)(nil),    // 9: tenders.Bid.CreateResponse
	(*Bid_ExecuteRequest)(nil),    // 10: tenders.Bid.ExecuteRequest
	(*Bid_ExecuteResponse)(nil),   // 11: tenders.Bid.ExecuteResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
}
var file_tenders_tenders_proto_depIdxs = []int32{
	12, // 0: tenders.Tender.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: tenders.Tender.CreateRequest.tender:type_name -> tenders.Tender
	0,  // 2: tenders.Tender.CreateResponse.tender:type_name -> tenders.Tender
	0,  // 3: tenders.Tender.GetResponse.tender:type_name -> tenders.Tender
	1,  // 4: tenders.Tender.CloseResponse.winning_bid:type_name -> tenders.Bid
	1,  // 5: tenders.Bid.CreateRequest.bid:type_name -> tenders.Bid
	1,  // 6: tenders.Bid.CreateResponse.bid:type_name -> tenders.Bid
	13, // 7: tenders.Bid.ExecuteResponse.elapsed:type_name -> google.protobuf.Duration
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_tenders_tenders_proto_init() }
func file_tenders_tenders_proto_init() {
	if File_tenders_tenders_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tenders_tenders_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tender_CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tender_CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tender_GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tender_GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tender_CloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tender_CloseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid_CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid_CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid_ExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tenders_tenders_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid_ExecuteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tenders_tenders_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tenders_tenders_proto_goTypes,
		DependencyIndexes: file_tenders_tenders_proto_depIdxs,
		MessageInfos:      file_tenders_tenders_proto_msgTypes,
	}.Build()
	File_tenders_tenders_proto = out.File
	file_tenders_tenders_proto_rawDesc = nil
	file_tenders_tenders_proto_goTypes = nil
	file_tenders_tenders_proto_depIdxs = nil
}
