version: '2.8'

services:
  server:
    build: .
    restart: unless-stopped
    cpus: 2
    mem_limit: 4G
    pids_limit: 512
    ports:
      - "9090:9090/udp"
    environment:
      GOMAXPROCS: '2'
      PG_DSN: 'host=db user=great_mettender password=great_mettender dbname=great_mettender port=5432 sslmode=disable'

  #    sysctls:
  #      - net.core.rmem_max=2500000

  db:
    image: postgres:15-alpine3.16
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'great_mettender'
      POSTGRES_PASSWORD: 'great_mettender'
      POSTGRES_DB: 'great_mettender'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./vol/db:/var/lib/postgresql/data
